// <auto-generated />
using System;
using KlaipedaCity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KlaipedaCity.Migrations
{
    [DbContext(typeof(KlaipedaDbContext))]
    partial class KlaipedaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KlaipedaCity.Models.Cuisine", b =>
                {
                    b.Property<int>("CuisineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuisineName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuisineID");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("KlaipedaCity.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HotelAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelPrice")
                        .HasColumnType("int");

                    b.Property<int>("HotelRating")
                        .HasColumnType("int");

                    b.HasKey("HotelID");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("KlaipedaCity.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CuisineNameCuisineID")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantPrice")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantRating")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID");

                    b.HasIndex("CuisineNameCuisineID");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("KlaipedaCity.Models.Restaurant", b =>
                {
                    b.HasOne("KlaipedaCity.Models.Cuisine", "CuisineName")
                        .WithMany()
                        .HasForeignKey("CuisineNameCuisineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
